DROP TABLE IF EXISTS TRANSFORMERS;

CREATE TABLE TRANSFORMERS(
     NAME VARCHAR(250) NOT NULL  PRIMARY KEY,
     FACTION VARCHAR(250) NOT NULL,
     STRENGTH INT NOT NULL,
     INTELLIGENCE INT NOT NULL,
     SPEED INT NOT NULL,
     ENDURANCE INT NOT NULL,
     RANK INT NOT NULL,
     COURAGE INT NOT NULL,
     FIREPOWER INT NOT NULL,
     SKILL INT NOT NULL,
     IS_ALIVE BOOLEAN NOT NULL
);

INSERT INTO TRANSFORMERS(NAME,FACTION,STRENGTH,INTELLIGENCE,SPEED,ENDURANCE,RANK,COURAGE,FIREPOWER,SKILL,IS_ALIVE )VALUES
('IRONHIDE','AUTOBOTS',3,3,3,3,3,3,3,15,true),
('JAZZ','AUTOBOTS',3,3,3,3,3,3,3,15,true),
('MEGATRON','DECEPTICONS',3,3,3,3,3,3,3,15,true)